openapi: 3.1.0
info:
  title: VitalHealth Analyzer Pro – PDF Service
  version: "1.0.0"

servers:
  - url: https://vitalhealth-analyzer.onrender.com

paths:
  /generate-pdf:
    post:
      summary: Generar informe cuántico en PDF (Base Caliber)
      operationId: generatePdf
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                estado_general:
                  type: object
                plan_30d:
                  type: object
                branding:
                  type: object
      responses:
        "200":
          description: PDF generado correctamente
          content:
            application/pdf:
              schema:
                type: string
                format: binary
